name: Build and Test
on:
  pull_request:
    types:
    - open
    - closed
    - synchronized

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    container:
      image: adoptopenjdk/openjdk13:alpine-slim
    steps:
      - name: Run tests
        run: |
          mvn test


